- name: demo on variables
  hosts: all
  vars:
    URL: sample.com
  tasks:
    - name: print URL name
      ansible.builtin.debug:
        msg: "{{ URL }}"



- name: demo on variable placed in the tasks
  hosts: all
  tasks:
    - name: print URL name
      ansible.builtin.debug:
        msg: "{{ URL }}"
  vars:
    URL: sample1.com


- name: demo on register variabls
  hosts: all
  tasks:
    - name:
      ansible.builtin.shell: uptime
      register: OUT
    - name: print out
      ansible.builtin.debug:
        msg: "{{ OUT }}"


- name: demo on register variable
  hosts: all
  tasks:
    - name: show system uptime
      ansible.builtin.shell: uptime
      register: OUT
    - name: print system time
      ansible.builtin.debug:
        msg: "{{ OUT }}"
